import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import BigButton from "../components/BigButton/BigButton";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lubimovka team-good-script components</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <BigButton color="accent" text="Смотреть читку" arrow='diagonal'/>
      <BigButton color="accent" text="Скачать пьесу" arrow='down'/>
      <BigButton text="Отправить" arrow='right'/>
    </div>
  )
}
